# fly.toml app configuration file generated for nameless-paper-7500 on 2023-11-07T10:47:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nameless-paper-7500"
primary_region = "lax"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]